import os


WINDOWWIDTH = 640
WINDOWHEIGHT = 480
FPS = 30
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
STARTING_LIVES = 3
PLAYER_SPEED = 5
WEAPON_SPEED = 12
ENEMY_SPEED = 8
BONUS_SPEED = 6
#DIR_PATH = os.path.dirname(__file__) + '/'
#IMAGES_PATH = DIR_PATH + 'images/'
